server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
